In [ ]:

# mlp for multi-label classification
from numpy import mean
from numpy import std
from numpy import asarray
import pandas as pd
from sklearn.datasets import make_multilabel_classification
from sklearn.model_selection import RepeatedKFold
from keras.models import Sequential
from keras.layers import Dense
from sklearn.metrics import accuracy_score
from sklearn import preprocessing


In [ ]:
X, y = make_multilabel_classification(n_samples=1000, n_features=10, n_classes=3, n_labels=2, random_state=1)
# summarize dataset shape
print(X.shape, y.shape)
# summarize first few examples
for i in range(10):
 print(X[i], y[i])

(1000, 10) (1000, 3)
[ 3.  3.  6.  7.  8.  2. 11. 11.  1.  3.] [1 1 0]
[7. 6. 4. 4. 6. 8. 3. 4. 6. 4.] [0 0 0]
[ 5.  5. 13.  7.  6.  3.  6. 11.  4.  2.] [1 1 0]
[1. 1. 5. 5. 7. 3. 4. 6. 4. 4.] [1 1 1]
[ 4.  2.  3. 13.  7.  2.  4. 12.  1.  7.] [0 1 0]
[ 4.  3.  3.  2.  5.  2.  3.  7.  2. 10.] [0 0 0]
[ 3.  3.  3. 11.  6.  3.  4. 14.  1.  3.] [0 1 0]
[ 2.  1.  7.  8.  4.  5. 10.  4.  6.  6.] [1 1 1]
[ 5.  1.  9.  5.  3.  4. 11.  8.  1.  8.] [1 1 1]
[ 2. 11.  7.  6.  2.  2.  9. 11.  9.  3.] [1 1 1]


In [ ]:
X.type()

In [ ]:
%cd drive/MyDrive

/content/drive/MyDrive


In [ ]:
%cd Project3:VDP/WebML

/content/drive/MyDrive/Project3:VDP/WebML


In [ ]:
dataset = pd.read_csv('df_speed.csv', index_col = False)

In [ ]:
Y = pd.read_csv('df_speed_YNumerical.csv', index_col = False)

In [ ]:
dataset

In [ ]:
Y

In [ ]:
dataset = dataset.to_numpy()
dataset

array([[0.02459016, 0.        , 0.01114206, ..., 0.50793651, 0.        ,
        0.49030656],
       [0.02224824, 0.        , 0.01671309, ..., 0.50793651, 0.        ,
        0.49011556],
       [0.01990632, 0.        , 0.01671309, ..., 0.50793651, 0.        ,
        0.49011556],
       ...,
       [0.03161593, 0.        , 0.02785515, ..., 0.50793651, 0.        ,
        0.48094738],
       [0.03044496, 0.        , 0.02228412, ..., 0.50793651, 0.        ,
        0.48085188],
       [0.02576112, 0.        , 0.01671309, ..., 0.50793651, 0.        ,
        0.48085188]])

In [ ]:
Y = Y.to_numpy()
Y

array([[1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       ...,
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]])

In [ ]:
# normalization
x = dataset.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
dataset = pd.DataFrame(x_scaled)

In [ ]:
# get the model
def get_model(n_inputs, n_outputs):
 model = Sequential()
 model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
 model.add(Dense(n_outputs, activation='sigmoid'))
 model.compile(loss='binary_crossentropy', optimizer='adam')
 return model
 


In [ ]:
dataset[1]

array([0.02224824, 0.        , 0.01671309, 0.11610427, 0.        ,
       0.        , 0.56284153, 0.5       , 0.50793651, 0.        ,
       0.49011556])

In [ ]:
Y.shape[1]

5

In [ ]:
# evaluate a model using repeated k-fold cross-validation
def evaluate_model(X, y):
 results = list()
 n_inputs, n_outputs = X.shape[1], y.shape[1]
 # define evaluation procedure
 cv = RepeatedKFold(n_splits=5, n_repeats=2, random_state=1)
 # enumerate folds
 for train_ix, test_ix in cv.split(X):
  # prepare data
  X_train, X_test = X[train_ix], X[test_ix]
  y_train, y_test = y[train_ix], y[test_ix]
  # define model
  model = get_model(n_inputs, n_outputs)
  # fit model
  model.fit(X_train, y_train, verbose=0, epochs=100)
  # make a prediction on the test set
  yhat = model.predict(X_test)
  # round probabilities to class labels
  yhat = yhat.round()
  # calculate accuracy
  acc = accuracy_score(y_test, yhat)
  # store result
  print('>%.3f' % acc)
  results.append(acc)
 return results
 


In [ ]:
# evaluate model
results = evaluate_model(dataset, Y)
# summarize performance
print('Accuracy: %.3f (%.3f)' % (mean(results), std(results)))

590/590 [==============================] - 1s 2ms/step
>0.671
590/590 [==============================] - 1s 984us/step
>0.779
590/590 [==============================] - 1s 965us/step
>0.818
590/590 [==============================] - 1s 1ms/step
>0.849
590/590 [==============================] - 1s 1ms/step
>0.720
590/590 [==============================] - 1s 995us/step
>0.749
590/590 [==============================] - 1s 1ms/step
>0.656
590/590 [==============================] - 1s 935us/step
>0.745
590/590 [==============================] - 1s 2ms/step
>0.842
590/590 [==============================] - 1s 977us/step
>0.715
Accuracy: 0.755 (0.064)


In [ ]:
results

[0.6708518753973299,
 0.7791375291375291,
 0.8176520449247722,
 0.8494384403475312,
 0.7204386522568341,
 0.7490993854630218,
 0.6564950201313837,
 0.7450731087094723,
 0.8420216147488875,
 0.7154058063148973]

In [ ]:
# get model
model = get_model(dataset.shape[1], Y.shape[1])
# fit the model on all data
model.fit(dataset, Y, verbose=1, epochs=100)
# make a prediction for new data
row = [3, 3, 6, 7, 8, 2, 11, 11, 1, 3]
newX = asarray([row])
#yhat = model.predict(newX)
#print('Predicted: %s' % yhat[0])

Epoch 1/100
2950/2950 [==============================] - 7s 2ms/step - loss: 0.3829
Epoch 2/100
2950/2950 [==============================] - 6s 2ms/step - loss: 0.2525
Epoch 3/100
2950/2950 [==============================] - 5s 2ms/step - loss: 0.1976
Epoch 4/100
2950/2950 [==============================] - 6s 2ms/step - loss: 0.1720
Epoch 5/100
2950/2950 [==============================] - 8s 3ms/step - loss: 0.1568
Epoch 6/100
2950/2950 [==============================] - 7s 2ms/step - loss: 0.1474
Epoch 7/100
2950/2950 [==============================] - 5s 2ms/step - loss: 0.1409
Epoch 8/100
2950/2950 [==============================] - 6s 2ms/step - loss: 0.1363
Epoch 9/100
2950/2950 [==============================] - 6s 2ms/step - loss: 0.1328
Epoch 10/100
2950/2950 [==============================] - 5s 2ms/step - loss: 0.1300
Epoch 11/100
2950/2950 [==============================] - 15s 5ms/step - loss: 0.1277
Epoch 12/100
2950/2950 [==============================] - 6s 2ms/step - l

In [ ]:
model.save('speed_MLP')

In [ ]:
row = [2, 3, 3, 6, 7, 8, 2, 11, 11, 1, 3]
newX = asarray([row])
yhat = model.predict(newX)
print('Predicted: %s' % yhat[0].round())

1/1 [==============================] - 0s 99ms/step
Predicted: [0. 1. 0. 0. 1.]
